config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'welcome/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'employees#index'
  resources :employees
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: [:show, :edit, :update, :destroy]
  skip_before_action :authenticate_user!, only: :destroy

  def index
    @employees = User.all
  end

  def show
  end

  def new
    @employee = User.new
  end

  def edit
  end

  def create
    @employee = User.new(employee_params)
    @employee.password = '123456'
    respond_to do |format|
      if @employee.save
        format.html { redirect_to employee_path @employee, notice: 'Employee was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @employee.update(employee_params)
        format.html { redirect_to employee_path @employee, notice: 'Employee was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @employee.destroy
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'Employee was successfully destroyed.' }
    end
  end

  private
    def set_employee
      @employee = User.find(params[:id])
    end

    def employee_params
      params.require(:user).permit(:first_name,:last_name,:email)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/employees/_form.html.erb
<%= form_with(model: employee,url: url,id: 'employee_form', local: true) do |form| %>
  <% if employee.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <ul>
      <% employee.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= form.label :first_name,'First Name' %>
    <%= form.text_field :first_name,class: 'form-control',placholder: 'Enter First Name' %>
  </div>
  <div class="form-group">
    <%= form.label :last_name,'Last Name' %>
    <%= form.text_field :last_name,class: 'form-control',placholder: 'Enter Last Name' %>
  </div>
  <div class="form-group">
    <%= form.label :email,'Email' %>
    <%= form.email_field :email,class: 'form-control',placholder: 'Enter Email' %>
  </div>
  <div class="form-group">
    <%= form.submit 'Submit',class: 'btn btn-sm btn-success'%>
  </div>
<% end %>

app/views/employees/edit.html.erb
<div class="row">
  <div class="col-md-3"></div>
  <div class="col-md-6">
    <div class="card">
      <div class="card-header"><h2>Editing Employee</h2></div>
      <div class="card-body">
        <%= render 'form', employee: @employee,url: employee_path %>
      </div>
      <div class="card-footer">
        <%= link_to 'Show', employee_path(@employee),class: 'btn btn-sm btn-secondary' %> |
        <%= link_to 'Back', employees_path %>
      </div>
    </div>
  </div>
</div>

app/views/employees/index.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="card">
      <div class="card-header"><h1>Employees</h1></div>
      <div class="card-body">
        <table class="table table-bordered table-striped">
          <thead>
          <tr>
            <th>Sr #</th>
            <th>First Name</th>
            <th>Last Name</th>
            <th>Email</th>
            <th colspan="3">Actions</th>
          </tr>
          </thead>
          <tbody>
          <% @employees.each_with_index  do |employee,index| %>
            <tr>
              <td><%=index+1 %></td>
              <td><%=employee&.first_name %></td>
              <td><%=employee&.last_name %></td>
              <td><%=employee&.email %></td>
              <td><%= link_to '<i class="fas fa-eye"></i>'.html_safe, employee_path(employee),class: 'btn btn-sm btn-secondary' %></td>
              <td><%= link_to '<i class="fas fa-edit"></i>'.html_safe, edit_employee_path(employee),class: 'btn btn-sm btn-warning' %></td>
              <td><%= link_to '<i class="fas fa-trash"></i>'.html_safe, employee_path(employee), method: :delete, data: { confirm: 'Are you sure?' },class: 'btn btn-sm btn-danger'%></td>
            </tr>
          <% end %>
          </tbody>
        </table>
      </div>
      <div class="card-footer">
      </div>
    </div>
  </div>
</div>

app/views/employees/new.html.erb
<div class="row">
  <div class="col-md-3"></div>
  <div class="col-md-6">
    <div class="card">
      <div class="card-header"><h2>New Employee</h2></div>
      <div class="card-body">
        <%= render 'form', employee: @employee, url: employees_path%>
      </div>
      <div class="card-footer">
        <%= link_to 'Back', employees_path %>
      </div>
    </div>
  </div>
</div>

app/views/employees/show.html.erb
<div class="row">
  <div class="col-md-3"></div>
  <div class="col-md-6">
    <div class="card">
      <div class="card-header"><h2><%=@employee&.first_name %> Employee</h2></div>
      <div class="card-body">
        <div class="form-group">
          <table class="table">
            <tbody>
              <tr>
                <td>First Name:</td>
                <td><strong><%=@employee&.first_name %></strong></td>
              </tr>
              <tr>
                <td>Last Name:</td>
                <td><strong><%=@employee&.last_name %></strong></td>
              </tr>
              <tr>
                <td>Email:</td>
                <td><strong><%=@employee&.email %></strong></td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
      <div class="card-footer">
        <%= link_to 'Edit', edit_employee_path(@employee),class: 'btn btn-sm btn-warning' %> |
        <%= link_to 'Back', employees_path %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
    <a class="navbar-brand" href="#">Coding</a>
    <% if user_signed_in? %>
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
      <li class="nav-item active">
        <a class="nav-link btn btn-sm btn-primary" href="<%=root_path %>">Employees<span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item active padding">
        <a class="nav-link btn btn-sm btn-primary" href="<%=new_employee_path %>">Add Employee<span class="sr-only">(current)</span></a>
      </li>
    </ul>
    <ul class="navbar-nav pull-right">
      <li class="nav-item active">
        <a class="nav-link" href="<%=root_path %>"><%=current_user&.email %><span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item active">
        <%=link_to 'Sign Out',destroy_user_session_path,method: :delete,class: 'nav-link' %>
      </li>
    </ul>
    <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Coding</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <style>
      .padding{
        padding-left: 2%!important;
      }
    </style>
  </head>

  <body>
    <div class="container-fluid">
      <%=render partial: 'layouts/navbar' %>
    </div>
    <div class="container">
      <% if params[:notice].present? %>
        <div id="notice" class="notice alert alert-success" role="alert">
          <%= params[:notice] %>
        </div>
      <% end %>
      <% if alert %>
        <div class="alert alert-danger" role="alert">
          <%= alert %>
        </div>
      <% end %>
      <%= yield %>
    </div>
  </body>
  <script>
      $(document).ready(function() {
          // show the alert
          setTimeout(function() {
              $(".alert").alert('close');
          }, 2000);

          jQuery.validator.addMethod("lettersonly", function(value, element) {
              return this.optional(element) || /^[a-z]+$/i.test(value);
          }, "Letters only please");

          $('#employee_form').validate({ // initialize the plugin
              rules: {
                  'user[first_name]': {
                      required: true,
                      minlength: 3,
                      maxlength: 20,
                      lettersonly: true
                  },
                  'user[last_name]': {
                      required: true,
                      minlength: 3,
                      maxlength: 20,
                      lettersonly: true
                  },
                  'user[email]': {
                      required: true,
                      email: true
                  }
              },
              messages :{
                  'user[first_name]' : {
                      required : 'Enter First Name',
                  },
                  'user[last_name]' : {
                      required : 'Enter Last Name',
                  },
                  'user[email]': {
                      required: 'Enter Email'
                  }
              }
          });
      });
  </script>
</html>

app/views/welcome/index.html.erb
<h1>Hello, Rails!</h1>